### ISSUE TITLE
Any plans to linux (and osx) arm64 binaries?

### ISSUE THREAD

**Issue by beroso** [abbr/deasync-bin#5]
I'm trying to run a node project on a **node:lts-alpine** on Mac m1, but it produces the following error:

```console
0 16.40 npm ERR! code 1
#0 16.40 npm ERR! path /app/node_modules/deasync
#0 16.40 npm ERR! command failed
#0 16.40 npm ERR! command sh -c node ./build.js
#0 16.40 npm ERR! gyp info it worked if it ends with ok
#0 16.40 npm ERR! gyp info using node-gyp@9.0.0
#0 16.40 npm ERR! gyp info using node@16.15.0 | linux | arm64
#0 16.40 npm ERR! gyp ERR! find Python 
#0 16.40 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#0 16.40 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#0 16.40 npm ERR! gyp ERR! find Python checking if "python3" can be used
#0 16.40 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#0 16.40 npm ERR! gyp ERR! find Python checking if "python" can be used
#0 16.40 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
#0 16.40 npm ERR! gyp ERR! find Python 
#0 16.40 npm ERR! gyp ERR! find Python **********************************************************
#0 16.40 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#0 16.40 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#0 16.40 npm ERR! gyp ERR! find Python you can try one of the following options:
#0 16.40 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#0 16.40 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#0 16.40 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#0 16.40 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#0 16.40 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#0 16.40 npm ERR! gyp ERR! find Python For more information consult the documentation at:
#0 16.40 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#0 16.40 npm ERR! gyp ERR! find Python **********************************************************
#0 16.40 npm ERR! gyp ERR! find Python 
#0 16.40 npm ERR! gyp ERR! configure error 
#0 16.40 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
#0 16.40 npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#0 16.40 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#0 16.40 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#0 16.40 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#0 16.40 npm ERR! gyp ERR! stack     at exithandler (node:child_process:406:5)
#0 16.40 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
#0 16.40 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
#0 16.40 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#0 16.40 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
#0 16.40 npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#0 16.40 npm ERR! gyp ERR! System Linux 5.10.104-linuxkit
#0 16.40 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#0 16.40 npm ERR! gyp ERR! cwd /app/node_modules/deasync
#0 16.40 npm ERR! gyp ERR! node -v v16.15.0
#0 16.40 npm ERR! gyp ERR! node-gyp -v v9.0.0
#0 16.40 npm ERR! gyp ERR! not ok 
#0 16.40 npm ERR! Build failed
#0 16.40 
#0 16.40 npm ERR! A complete log of this run can be found in:
#0 16.40 npm ERR!     /root/.npm/_logs/2022-05-05T17_03_08_751Z-debug-0.log
```

At the time, I edited the Dockerfile to include python as follow:
`RUN apk add --update python3 make g++`

But it would be nice if it had the arm64 binaries.

**Comment by jakiestfu** [comment]
+1 to this. I can't use this package on an M1

**Comment by abbr** [comment]
If there is a free service for running ci pipeline on said os/arch, maybe. The GH actions I use doesn’t have the option, yet.
